<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CategorySeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'title' => 'Santunan Untuk Kesehatan Dan Persalinan',
                'caption' => 'Sauyunan',
                'description' => 'Merupakan santunan kesehatan persalinan kepada masyarakat yang kurang mampu, yang akan melahirkan, dalam rangka menyelamatkan kesehatan anak dan ibu serta meningkatkan pelayanan kesehatan bagi masyarakat.',
                'image' => 'category-sauyunan.jpeg',
                'slug' => 'sauyunan',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Bangun Landasan Desa, Insyaaloh Damai Sejahtera',
                'caption' => 'Balad Indra',
                'description' => 'Merupakan suatu peraturan yang dibuat dan disepakati bersama olhe Kepala Desa dan Bada Permusyawaratan Desa (BPD) sebagai landasan hukum atau pijakan pemerintah desa dalam kegiatannya',
                'image' => 'category-balad-indra.jpeg',
                'slug' => 'balad-indra',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Jumat Menyapa',
                'caption' => 'Jumpa',
                'description' => 'Merupakan kegiatan dijari Jumat, menyapa masyarakat desa, sebagai upaya meningkatkan peran serta masyarakat dalam pelaksaaan jumat bersih.',
                'image' => 'category-jumpa.jpeg',
                'slug' => 'jumpa',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Kerja Warga Bareng Indra',
                'caption' => 'Jawara',
                'description' => 'Upaya menciptakan sinergitas antara pemerintah desa dengan Masyarakat dalam rangka mewujudkan hubungan kehidupan masyarakat yang humanis, dan mengedepankan sikap gotong royong.',
                'image' => 'category-jawara.jpeg',
                'slug' => 'jawara',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Melayani Masyarakat Sukamanah Dengan Ramah',
                'caption' => 'Mernah',
                'description' => 'Adalah upaya meningkatkan kinerja perangkat desa melalui pelayanan yang ramah terhadap masyarakat, melakukan 5 M yaitu SENYUM, SALAM, SAPA, SOPAN, dan SANTUN.',
                'image' => 'category-mernah.jpeg',
                'slug' => 'mernah',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Bazar Murah Jual Sembilan Bahan Pokok',
                'caption' => 'Baju Koko',
                'description' => 'Adalah kegiatan bazar jual sembako untuk masyarakat yang kurang mampu.',
                'image' => 'category-baju-koko.jpeg',
                'slug' => 'baju-koko',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Bersama Jaga Malam Amankan Rumah',
                'caption' => 'Berjamaah',
                'description' => 'Kegiatan meningkatkan sistem keamanan lingkuangan, melalui kegiatan ronda malam yang terjadwal disetiap RT/RW, sebagai upaya menciptakan lingkungan yang nyaman, aman dan tertib.',
                'image' => 'category-berjamaah.jpeg',
                'slug' => 'berjamaah',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Gerakan Ayo Sekolah Lagi',
                'caption' => 'Gosali',
                'description' => 'Kegiatan pemberdayaan Sumber Daya Manusia (SDM), dalam rangka meningkatkan Indeks Pembangunan Manusia (IPM), melalui kegiatan belajar masyarakat (pendidikan nonformal) yang berpusat di tingkat RT atau RW melalui Pendidikan Kesetaraan berbasis Life Skill/Vokasi/KWU, upaya meningkatkan IPM atau rara-rata lama sekolah di Desa Sukamanah.',
                'image' => 'category-gosali.jpeg',
                'slug' => 'gosali',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Bangun Infrastuktur Sarana Jeung Lembur',
                'caption' => 'Batur Salembur',
                'description' => 'Adalah pelaksanaan pembangunan sarana dan prasarana infrastruktur desa yang efesien, berkesinambungan, serta meningkatkan partisipasi masyarakat (semangat gotong royong).',
                'image' => 'category-batur-salembur.jpeg',
                'slug' => 'batur-salembur',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Bersama Tuntaskan Sampah Sukamanah',
                'caption' => 'Bertuah',
                'description' => 'Adalah kegiatan sosialisasi dan penangan terhadap penanggulangan sampah di Desa Sukamanah, dalam rangka menciptakan Lingkungan Hidup yang asri, sehat, dan bersih.',
                'image' => 'category-bertuah.jpeg',
                'slug' => 'bertuah',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Sukamanah Gemar Membaca Al-Qur\'an',
                'caption' => 'Sugema',
                'description' => 'Merupakan kegiatan pemberian bantuan kepada santri dan siswa berprestasi yang mampu/hafal alquran. Kegiatan ini dalam rangka meningkatkan motivasi belajar para siswa dan santri.',
                'image' => 'category-sugema.jpeg',
                'slug' => 'sugema',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Kegiatan Ekonomi Kerakyatan Berbasis Kearifan Lokal',
                'caption' => 'Kerak Telor',
                'description' => 'Adalah kegiatan Pemberdayaan Ekonomi Kerakyatan melalui (UMKM) yang terintegrasi dengan BUMDesa sesuai potensi keatifan lokal dan atau (industri rumah tangga), dalam rangka meningkatkan Daya Beli Masyarakat.',
                'image' => 'category-kerak-telor.jpeg',
                'slug' => 'kerak-telor',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Pengajian Peuting Keliling',
                'caption' => 'Pepeling',
                'description' => 'Merupakan kegiatan pengajian rutin keliling yang dilakukan oleh Aparatur Desa, sebagai upaya mewujudkan kualitas manusia yang beriman kepada Tuhan YME.',
                'image' => 'category-pepeling.jpeg',
                'slug' => 'pepeling',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Sistem Informasi, Pelayanan Terpadu Dan Terintegrasi',
                'caption' => 'Simpati',
                'description' => 'Sebuah aplikasi pelayanan berbasis digital untuk mempermudah warga masyarakat mendapatkan pelayanan yang bersifat administratif serta mempermudah warga mendapatkan informasi informasi yang berkaitan dengan Pemerintah Desa Sukamanah.',
                'image' => 'category-simpati.jpeg',
                'slug' => 'simpati',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Bantuan Sembako Kanggo Jompo',
                'caption' => 'Bako Pedo',
                'description' => 'Merupakan bantuan kepada jompo, hasil dari PAD atau aset desa, sebagai upaya meningkatkan kesejahteraan masayarakat khususnya lansia/manula.',
                'image' => 'category-bako-pedo.jpeg',
                'slug' => 'bako-pedo',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Gerakan Muda Mudi Masuk Masjid/Madrasah',
                'caption' => 'Gemma',
                'description' => 'Merupakan kegiatan penguatan regenerasi kepada para pemuda dan pemudi, dalam rangka meningkatkan iman dan taqwa kepada Tuhan Yang Maha Esa.',
                'image' => 'category-gemma.jpeg',
                'slug' => 'gemma',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Gerakan Menanam Pohon Di Lembur',
                'caption' => 'Gempur',
                'description' => 'Merupakan kegiatan penghijauan yang dilaksanakan kampung-kampung, sebagai upaya pelestarian Lingkungan Hidup yang indah, asri, dan hijau',
                'image' => 'category-gempur.jpeg',
                'slug' => 'gempur',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Kelompok Pemberdayaan Pemuda Produktif',
                'caption' => 'Keprok',
                'description' => 'Adalah kegiatan pemberdayaan berupa pelatihan, kursus keterampilan atau kegiatan kewirausahaan, dalam rangka pembinaan pemberdayaan ekonomi, sebagai upaya menciptakan masyarakat yang siap kerja, berwirausaha dan berdaya saing.',
                'image' => 'category-keprok.jpeg',
                'slug' => 'keprok',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Pelayanan Kesehatan Masyarakat Sukamanah',
                'caption' => 'Ketan Merah',
                'description' => 'Adalah kegiatan meningkatkan pelayanan kesehatan masyarakat, mengoptimalisasikan Balai Kesehatan yang terjadwal, serta pemberian makanan tambahan di posyandu untuk pencegahan Stunting.',
                'image' => 'category-ketan-merah.jpeg',
                'slug' => 'ketan-merah',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Bincang Warga Bareng Indra',
                'caption' => 'Bicara',
                'description' => 'Merupakan kegiatan komunikasi, dalam rangka tukar pendapat dan menyerap aspirasi masyarakat desa, melalui Musyawarah Rukun Tetangga (RT), Rukun Warga (RW), dan Musyawarah Dusun atau Desa.',
                'image' => 'category-bicara.jpeg',
                'slug' => 'bicara',
                'tag' => 'Program Desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('categories')->insertBatch($data);
    }
}
